improv

diff --git a/bin/etc/pingger b/bin/etc/pingger
--- a/bin/etc/pingger
+++ b/bin/etc/pingger
@@ -4,8 +4,8 @@
 #since 08-07-2019
 #License GPL3+
 
-pinggerversion=V7.5
-pinggerdate=28-07-2020
+propversion=V7.6
+propdate=29-08-2020
 
 # Colors
 GREEN='\e[01;32m'
@@ -25,6 +25,8 @@ N='\e[0m'
 base=/data/media/0/pingger
 log=$base/pingger.log
 data=$base/data
+base2=/data/local/pingger
+bin2=$base2/bin
 
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 #Functions
@@ -59,49 +61,98 @@ loadings() {
 
 
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
+# LIST APPS
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
-gappslist="
-com.android.vending
-com.google.android.gms
-"
-
-syslist="
+system_list="
 org.lineageos.snap
 "
+apps_list="
+code.name.monkey.retromusic
+"
 
-termlist="com.termux|com.termoneplus"
+blacklist_term="
+com.termux
+com.termoneplus
+jackpal.androidterm
+"
+blacklist_system="
+com.google.android.inputmethod.latin
+com.google.android.gms
+"
+blacklist_apps="
+com.mixplorer
+com.google.android.apps.messaging
+com.google.android.play.games
+ch.deletescape.lawnchair.plah
+"
 
-gamelist="com.mobile.legends"
+blacklist_game="
+com.mobile.legends
+com.tencent.ig
+com.supercell.clashofclans
+"
+
+if [ -f $data/black_list_gaming2 ]; then
+blacklist_gaming="$(cat $data/black_list_gaming2)"
+fi
+
+
+black_func(){
+	for zzz in $blacklist_apps $blacklist_game $blacklist_system $blacklist_term; do
+		[[ "$1" == $zzz ]] && return 0
+	done
+	}
 
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
+
+menu(){
+	while true; do
+	clear
+	print "$BLUE                    $2 $GREEN"
+	print
+	$1
+	print
+	print "${CYAN}1.Back To Menu      ${GREEN}2.Refresh"
+	print
+	echo -n "${WHITE}Select menu : ${NC}$GREEN"
+	read anjay
+	if [ $anjay -eq 1 ]; then
+	break
+	elif [ $anjay -eq 2 ]; then print;
+	else
+	print
+	error "Please select 1 or 2"
+	print
+	sleep 2s
+	fi
+	done
+}
 
 boost(){
 print "- Boost...";
-sleep 2
 print " ";
 for z in $(pm list packages -3) $gappslist $syslist; do
 boost6071=`getp1 $z`
    case $boost6071 in
-     com.termux|com.termoneplus)
-            print "- Skipping Terminal"
-            	;;
-              *)
-             print "- Boost : $boost6071"
-             am force-stop $boost6071 2>/dev/null
-				;;
-	esac
+     com.termux | com.termoneplus )
+        print "${YELLOW}[SKIP] •> ${WHITE}${boost6071//com.}"
+        ;;
+        
+     *)   
+        am force-stop $boost6071 && print "${GREEN}[OK] •> ${WHITE}${boost6071//com.}" || print "${RED}[ERROR] •> ${WHITE}${boost6071//com.}" 2>/dev/null
+     ;;
+    esac  
 done
 print "- Done ";
 }
 
 device(){
 	print
-	PRODUCT=$(getprop ro.product.vendor.device)
     ROM=$(getprop ro.build.display.id | cut -d'-' -f1)
-	print "Name ROM = $ROM ($PRODUCT) " |  tee -a $log;
-	AV=$(getprop ro.build.version.release)
-	print "Android Version = $AV " |  tee -a $log;
+	print "Name ROM = $ROM ($(getprop ro.product.vendor.device)) "
+	print "Android Version = $(getprop ro.build.version.release)" |  tee -a $log;
+	print "Android Security patch = $(getprop ro.build.version.security_patch)"
 	print "Baterai Status = $(cat /sys/class/power_supply/battery/status)"
 	print "Baterai = $(cat /sys/class/power_supply/battery/capacity)%"
 	print "Baterai Technology = $(cat /sys/class/power_supply/battery/technology)"
@@ -113,15 +164,15 @@ device(){
 	print "Kernel = $(uname -r)" |  tee -a $log;
 	print "Chipset = $(getprop ro.product.board) " |  tee -a $log;
 	print "GPU = $(cat /sys/kernel/gpu/gpu_model)"
-	for i in /system/xbin/busybox /sbin/busybox /system/bin/busybox
+	for i in /system/xbin/busybox /sbin/busybox /system/bin/busybox /vendor/bin
 	do
-	[ -f $i ] && print "Busybox = Installed" || print "Busybox = Not found"
+	[ -f $i ] && print "Busybox = Installed" || print "${WHITE}Busybox = Not found $GREEN"
 	 break 
     done
     [ -f /data/adb/magisk/magisk ] && print "Magisk = Installed" || print "magisk = Not found"
-    [ "$(getprop persist.vendor.camera.HAL3.enabled)" -eq 1 ] && print "Camera2api = Enable" || print "Camera2api = disable"
-    [ "$(grep f2fs /vendor/etc/fstab.qcom)" ] && print "F2FS : This ROM supports F2FS" || print "F2FS : This ROM not supports F2FS"
-    [ "$(cat /sys/kernel/touchpanel/dclicknode)" -eq 1 ] && print "DT2W : Enable" || print "DT2W : Disable"
+    [ "$(getprop persist.vendor.camera.HAL3.enabled)" -eq 1 ] && print "Camera2api = Enable" || print "${WHITE}Camera2api = Disable $GREEN"
+    [ "$(grep f2fs /vendor/etc/fstab.qcom)" ] && print "F2FS = This ROM supports F2FS" || print "${WHITE}F2FS = This ROM not supports F2FS${GREEN}"
+    test -f /sys/kernel/touchpanel/dclicknode && [ "$(cat /sys/kernel/touchpanel/dclicknode)" -eq 1 ] && print "DT2W = Enable" || print "${WHITE}DT2W = Disable${GREEN}"
     }
 	
 gaming1(){
@@ -131,109 +182,107 @@ gaming1(){
 	print " ";
 		for z in $(pm list packages -3) $gappslist $syslist; do
 			boost6071=`getp1 $z`
-  			 case $boost6071 in
-  				   com.termux|com.termoneplus|com.mixplore)
-           				 print "- ${RED}Skipping Terminal --> ${WHITE}$boost6071${WHITE}"
-           				 ;;
-            		 ${gamelist})
-            		 		print "- ${RED}Skipping Game --> ${WHITE}$boost6071"
-            		 		;;
-            		 		*)
-            				 print "- Force stop --> $boost6071 ${GREEN}successfully${WHITE}"
-             				am force-stop $boost6071 2>/dev/null
-							;;
-				esac
+  			 if black_func $boost6071; then
+			 	  print "${YELLOW}[SKIP] •> ${WHITE}${boost6071//com.}"
+			   else	  
+			 	  am force-stop $boost6071 2>/dev/null | >/dev/null && print "${GREEN}[OK] •> ${WHITE}${boost6071//com.}" || print "${RED}[ERROR] •> ${WHITE}${boost6071//com.}"
+			   fi
  		 done
  	print "- ${GREEN}Done${WHITE}"
      sleep 60s & loadings "- Loading ..."
  	done		
 }
+
+
 gaming2(){
-	if [ -f $data/gaming_mode_2 ]; then
+	if [ ! -f $data/gaming_mode_2 ]; then
 	clear
 	print
-	print "- Disabling Gaming Mode 2"
-	sleep 2s
-	printmid "${BRED}Gaming Mode 1${NC}$WHITE"
+	printmid "${CYAN}Gaming Mode 2${NC}$WHITE"
 	print " ";
-		for z in $(pm list packages -3) $gappslist $syslist; do
+	del $data/gaming2_list_apps
+		for z in $(pm list packages -3); do
 			boost6071=`getp1 $z`
-  			 case $boost6071 in
-  				   com.termux|com.termoneplus|com.mixplore)
-           				 print "- ${RED}Skipping Terminal --> ${WHITE}$boost6071${WHITE}"
-           				 ;;
-            		 ${gamelist})
-            		 		print "- ${RED}Skipping Game --> ${WHITE}$boost6071"
-            		 		;;
-            		 		*)
-            				 print "- Force stop --> $boost6071 ${GREEN}successfully${WHITE}"
-             				am force-stop $boost6071 2>/dev/null
-							;;
-				esac
- 		 done
+			 if black_func $boost6071; then
+			 	  print "${YELLOW}[SKIP] •> ${WHITE}${boost6071//com.}"
+			 else	  
+			 	  pm disable $boost6071 2>/dev/null | >/dev/null && print "${GREEN}[OK] •> ${WHITE}${boost6071//com.}" || print "${GREEN}[ERROR] •> ${WHITE}${boost6071//com.}"
+			 	  echo "$boost6071" >> $data/gaming2_list_apps
+			 fi
+ 	   done
+ 	echo actived > $data/gaming_mode_2
  	print "- ${GREEN}Done${WHITE}"
-     sleep 60s & loadings "- Loading ..."
- 	done		
-	rm -rf $data/gaming_mode_2
-	print " -Done"
-	sleep 2s
-	else
+ 	sleep 6s
+	elif [ -f $data/gaming_mode_2 ]; then
 	clear
-	print 
-	print "               Gaming Mode 2"
-	print 
-	print "- Enabling Gaming Mode 2"
-	sleep 2s
-	pingger_app_list pm disable gaming2 2>/dev/null
-	print "activated" > $data/gaming_mode_2
+	printmid "${BRED}DisablingGaming Mode 2${NC}$WHITE"
+		 while IFS=' ' read -r gaming2_apps; do
+		 	pm enable $gaming2_apps 2>/dev/null | >/dev/null  && print "${GREEN}[OK] •> ${WHITE}${gaming2_apps//com.}" || print "${RED}[ERROR] •> ${WHITE}${gaming2_apps//com.}"
+		 done < $data/gaming2_list_apps
+	del $data/gaming2_list_apps
+	del $data/gaming_mode_2
 	print "- Done"
-	sleep 2s
+	sleep 6s
 	fi
 	}
 gaming3(){
 	status_gaming3=$data/gaming_mode_3
 	list_gaming3=$data/gaming_mode_3_list
-	[ ! -f $list_gaming3 ] && error "$list_gaming3 Not found list app" && sleep 7s && return 0;
+	[ ! -f $list_gaming3 ] && [ ! $(grep . $list_gaming3) ] && error "$list_gaming3 Not found list app" && sleep 7s && return 1;
 	if [ -f $status_gaming3 ]; then
-	clear
-	print
-	print "- Disabling Gaming Mode 2"
-	sleep 2s
-	rm -rf $status_gaming3
-	print " -Done"
-	sleep 2s
-	while read gaming3_list;
-	do
-	pm enable $gaming3_list
-	done < $list_gaming3
+		clear
+		printmid "${BRED}Disabling Gaming Mode 2 ${NC}$GREEN"
+		print
+		sleep 1s
+		while IFS=' ' read -r gaming3_list; do
+			pm enable $gaming3_list 2>/dev/null | >/dev/null && print "${GREEN}[OK] •> ${WHITE}${gaming3_list//com.}" || print "${RED}[ERROR] •> ${WHITE}${gaming3_list//com.}"
+		done < $list_gaming3
+		
+		rm -rf $data/gaming_mode_3
+		print "${GREEN}- Done"
+		sleep 5s
 	else
 	clear
-	print 
-	print "               Gaming Mode 3"
-	print 
-	print "- Enabling Gaming Mode 3"
-	sleep 2s
-	while read gaming3_list;
-	do
-	pm disable $gaming3_list
-	done < $list_gaming3
-	print "activated" > $status_gaming3
-	print "- Done"
-	sleep 2s
+		printmid "${BRED}Enabling Gaming Mode 2${NC}${GREEN}"
+		print
+		sleep 1s
+		while IFS=' ' read -r gaming3_list; do
+			pm disable $gaming3_list 2>/dev/null | >/dev/null && print "${GREEN}[OK] •> ${WHITE}${gaming3_list//com.}" || print "${GREEN}[ERROR] •> ${WHITE}${gaming3_list//com.}"
+		done < $list_gaming3
+		echo actived > $status_gaming3
+		print "${GREEN}- Done"
+		sleep 5s
 	fi
+	
+	}
+	
+#
+about_game(){
+	print "1.Gaming Mode 1"
+	print "${YELLOW}the way this mode works is to force quit the app every 60 seconds to give the signal more focus to the game.${GREEN}"
+	print
+	print "2.Gaming mode 2"
+	print "${YELLOW}This mode is more aggressive because it will disable all installed applications, except games, so that the internet connection focuses on the game.${GREEN}"
+	print
+	print "4.Gaming Mode 3"
+	print "${YELLOW}This mode is almost the same as <gaming mode 2>, which distinguishes you from adding a list of applications that you disable. $GREEN"
+	print "${VIOLET}You can add the application package name in <${data}/gaming_mode_3> ${GREEN}"
+	print
+	
 	}
 	
 gaming(){
 	while true; do
 	clear
-	[ -f $data/gaming_mode_2 ] && gaming22="Disable Gaming Mode 2" || gaming22="Gaming Mode 2 (aggresive)"
-	[ -f $data/gaming_mode_3 ] && gaming23="Disable Gaming Mode 3" || gaming23="Gaming Mode 3"
+	[ -f $data/gaming_mode_2 ] && gaming22="${VIOLET}2.Disable Gaming Mode 2${GREEN}" || gaming22="2.Gaming Mode 2 (Not Recomended)"
+	[ -f $data/gaming_mode_3 ] && gaming23="${VIOLET}3.Disable Gaming Mode 3${GREEN}" || gaming23="3.Gaming Mode 3"
 	print "$YELLOW                  Gaming Mode Select $GREEN"
 	print
 	print "1.Gaming Mode 1"
-	print "2.$gaming22"
-	print "3.$gaming23"
-	print "4.Exit"
+	print "$gaming22"
+	print "$gaming23"
+	print "4.About"
+	print "5.Exit"
 	print
 	echo -n "Select Gaming Mode : "
 	read gamemodeselect
@@ -242,32 +291,30 @@ gaming(){
 	1) gaming1 ;;
 	2) gaming2 ;;
 	3) gaming3 ;;
-	4) break ;;
+	4) menu about_game "About Gaming Mode" ;;
+	5) break ;;
 	*) error "Invalid selection"; sleep 2s ;;
 	esac
 	done
 	}
 battery(){
 	if [ ! -f $data/battery_saver ]; then
-	print "            Enabling Baterry saver"
+	print "${CYAN}Enabling Battery Saving${NC}$WHITE"
 		for z in $(pm list packages -3) $gappslist $syslist; do
 		boost6071=`getp1 $z`
-   		case $boost6071 in
-    			 com.termux|com.termoneplus)
-            	 print "- Skipping Terminal"
-            		;;
-             	 *)
-            		 print "- Force stop : $boost6071"
-            		 am force-stop $boost6071 2>/dev/null
-				;;
-			esac
+   		if black_func $boost6071; then
+   		   print "${CYAN}[SKIP] •> ${WHITE}${boost6071//com.}"
+   		else   
+   		   print "${GREEN}[OK] •> ${WHITE}${boost6071//com.}"
+   		   am force-stop $boost6071 2>/dev/null
+   		fi   
 		done
-		pm disable com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver
+		pm disable com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver >/dev/null
 		print "actived" > $data/battery_saver
 		print "- Done ";
 	elif [ -f $data/battery_saver ]; then
-		print "               Disable Battery saver"
-		pm enable com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver
+		print "${CYAN}Disabling Battery Saving${NC}$WHITE"
+		pm enable com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver >/dev/null
 		del $data/battery_saver
 		print "- Done"
 	fi
@@ -441,7 +488,23 @@ ccg(){
 	}
 
 testping(){
-	ping -w 10s google.com
+	print
+	for pingwhhx in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
+		coreping=`ping -w 3s google.com | tail -5 | grep time= | cut -d' ' -f8 | cut -d = -f2 | cut -d . -f1`
+			if [ ! "$coreping" ]; then
+				print "${RED} PING ${WHITE}•> ${RED}Server not respon"
+			elif [ "$coreping" -lt 30 ]; then
+				print "${GREEN} PING ${WHITE}•>${GREEN} $coreping STATUS •> Very Good"
+			elif [ "$coreping" -lt 70 ]; then
+				print "${GREEN} PING ${WHITE}•>${GREEN} $coreping STATUS •> Good"
+			elif [ "$coreping" -lt 100 ]; then
+				print "${YELLOW} PING ${WHITE}•>${YELLOW} $coreping STATUS •> Medium"
+			elif [ "$coreping" -lt 120 ]; then
+				print "${VIOLET} PING ${WHITE}•>${VIOLET} $coreping STATUS •> Unstable"
+			else
+			 print "${RED} PING •> $coreping STATUS •> very unstable"
+			fi 
+	done
 	}
 	
 meminfo(){
@@ -463,7 +526,7 @@ meminfo(){
 	}
 about(){
 print "$CYAN "
-print "Pingger Stable Control $pinggerversion ($pinggerdate)"
+print "Pingger Stable Control $propversion ($propdate)"
 print "Copyright (C) 2020 wahyu kurniawan (wahyu6070)."
 print "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>."
 print "This is free software: you are free to change and redistribute it."
@@ -476,28 +539,7 @@ print " Telegram: https://t.me/wahyu6070group"
 print " $GREEN"
 }
 
-menu(){
-	while true; do
-	clear
-	print "$BLUE                    $2 $GREEN"
-	print
-	$1
-	print
-	print "${CYAN}1.Back To Menu      ${GREEN}2.Refresh"
-	print
-	echo -n "${WHITE}Select menu : ${NC}$GREEN"
-	read anjay
-	if [ $anjay -eq 1 ]; then
-	break
-	elif [ $anjay -eq 2 ]; then print;
-	else
-	print
-	error "Please select 1 or 2"
-	print
-	sleep 2s
-	fi
-	done
-}
+
 
 #
 #Root
@@ -506,7 +548,7 @@ if [ "$id" != "0" ] && [ "$id" != "root" ]; then
 print " "
 error "Root Accest Not Found $WHITE"
 print " "
-exit
+exit 1
 fi
 
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
@@ -515,15 +557,15 @@ test ! -d $data && cdir $data
 #▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 while true; do
 clear
-test -f $data/battery_saver && batterystatus="${RED}Disable Battery... ${NC}${GREEN}" || batterystatus="Battery Saver      "
+test -f $data/battery_saver && batterystatus="${VIOLET}3.Disable Battery... ${NC}${GREEN}" || batterystatus="3.Battery Saver      "
 print " "
 print "     ${YELLOW}Pingger ${GREEN}Stable ${WHITE}Control $GREEN"
 print " "
 print "1.Boost              6.Memory Info"
 print "${YELLOW}2.Gaming Mode${GREEN}        7.Device Info"
-print "3.${batterystatus}8.Add on"
+print "${batterystatus}8.Add on"
 print "4.Check Ping         9.About"
-print "5.CCG                10.Exit"
+print "5.Clean Cache        10.Exit"
 print
 echo -n "Choose one of the numbers : "
 read pilih
@@ -531,7 +573,7 @@ case $pilih in
 1) menu boost Boost ;;
 2) gaming ;;
 3) menu battery "Battery Saver" ;;
-4) menu testping "Tes Ping" ;;
+4) menu testping "Test Ping" ;;
 5) menu ccg "Cleaning Cache Game" ;;
 6) menu meminfo "Memory Info" ;;
 7) menu device "Device info" ;;
